### ISSUE TITLE
Go over unit tests for main function and identify the missing use cases

### ISSUE THREAD

**Issue by andywaltlova** [oamg/convert2rhel-worker-scripts#47]
Someone needs to go over various scenarios that can occur during preconversion/conversion and create complete set of unit tests for main function

- create case table (e.g. c2r pkg installed for successful and unsuccessful conversion, same for c2r pkg just updated etc.)
- create/update the unit tests - do it in some sane way, multiple files, fixtures or parametrize

Beware that the coverage percentage is not sufficient metric to consider your work done.

**Comment by andywaltlova** [comment]
Add asserts to tests to at least assert that output has expected messages for UI or that the output isn't empty, create some fixture (maybe use some builtin fixture?)

**Comment by r0x0d** [comment]
do we still need that issue, @andywaltlova?

**Comment by andywaltlova** [comment]
No I did it in #56  when I was refactoring tests. I think it is good enough now.
