### ISSUE TITLE
Name change

### ISSUE THREAD

**Issue by r0x0d** [oamg/convert2rhel-worker-scripts#6]
What about changing the repo name to something like "convert2rhel-worker-scripts"? As in the future, we could have different scripts in this repo instead of creating new ones.

**Comment by andywaltlova** [comment]
Sure, that seems like a better name :) I don't really have preference

**Comment by r0x0d** [comment]
Thanks!

**Comment by SpyTec** [comment]
I'd change it to `convert2rhel-worker-script` to be the same format as `rhc-worker-script`. I.e. removing the s at the end

**Comment by SpyTec** [comment]
Fair point
